name: npm-preview

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GitHub repository URL to build and publish'
        required: true
        type: string

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run build script
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git config --local url."https://api:${{ github.token }}@github.com/".insteadOf "https://github.com/"
          git config --local url."https://ssh:${{ github.token }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --local url."https://git:${{ github.token }}@github.com/".insteadOf "git@github.com:"
          node .github/scripts/ci.mjs "${{ inputs.repo }}"